# Flask-RESTful-API

## GET USERS
GET http://127.0.0.1:5000/users

### GET USER BY QUERY ["id", "username", "email", phone_number]
GET http://127.0.0.1:5000/users/id=64754223ed9aa739f37300f5

# invalid request
GET http://127.0.0.1:5000/users/1


### GET USER BY USERNAME
GET http://127.0.0.1:5000/users/username=admin

### GET USER BY EMAIL
GET http://127.0.0.1:5000/users/email=info@johnmuller.eu




### DELETE USER by QUERY 
DELETE http://127.0.0.1:5000/users/id=6475431b142e79578265f617

### Verify that the user has been deleted
GET http://127.0.0.1:5000/users/id=6475431b142e79578265f617


#POST REQUESTS

### Register 
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "register_credentials": {
        "username": "admin5",
        "name": "adimn5",
        "email": "admin5@deai.com",
        "password": "admin",
        "phone_number": "79000005",
        "role": "admin"
    }
}

### Login 
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "login_credentials": {
        "email": "admin5@deai.com",   
        "password": "admin"
    } 
}

#### Messages 

###
GET http://127.0.0.1:5000/conversations

###

POST http://127.0.0.1:5000/conversations
Content-Type: application/json

{
    
    "conversation_id" : "649e19e845620564c6eb5669",
    "sender": "6475431b142e79578265f617",
    "receiver": "6475431b142e79578265f617",
    "message": "Hello"
    
}

### Get messages by conversation id

GET http://127.0.0.1:5000/conversations/649e1c92d19172a166d1fe82

### Delete Conversation by id
DELETE http://127.0.0.1:5000/conversations/649e1c92d19172a166d1fe82

### Update Title

PUT http://127.0.0.1:5000/conversations/649e1c92d19172a166d1fe82
Content-Type: application/json

{
    "title": "This is a new title"
}
